name: ExcellentJobs
main: su.nightexpress.excellentjobs.JobsPlugin
version: '${project.version}'
api-version: 1.21
folia-supported: true
description: A better & elegant jobs solution for your server!
author: NightExpress
depend: [ nightcore ]
softdepend:
  - PlaceholderAPI
  - ProtocolLib
  - MythicMobs
  - EvenMoreFish
  - CustomFishing
